# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.21.5)

# Forge
forge_id=forge
forge_version=52.1.0
forge_version_range=[52,)

mapping_channel=official
mapping_version=1.21.4

# NeoForge
neoforge_id=neoforge
neogradle.subsystems.parchment.minecraftVersion=1.21.4
neogradle.subsystems.parchment.mappingsVersion=2025.03.23
neo_version=21.4.154
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=xiao.cbraddon
mod_id=cbraddon
mod_name=CBR addon
mod_license=GPL-3.0 license
mod_version=0.4.4-dev3
mod_credits=XiaoColorful, XColorful
mod_authors=XiaoColorful
mod_description=Custom BattleRoyale Feature Expansion

mod_issue_url=https://github.com/XColorful/CBR-addon/issues
mod_display_url=https://github.com/XColorful/CBR-addon/wiki
mod_logo_file=logo.png

pack_description=CBR addon resources
pack_format=15

# Dependencies
battleroyale_version_range=[0.4.4-dev3,)

# CompileOnly
# battleroyale-0.4.4-forge1.21.1.jar
battleroyale_curse_maven=curse.maven:custom-battleroyale-1277855:7142979
# battleroyale-0.4.4-neoforge1.21.4.jar
battleroyale_neoforge_curse_maven=curse.maven:custom-battleroyale-1277855:7143245