modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/XColorful/CBR-addon/issues"

[[mods]]
modId="cbraddon"
version="${mod_version}"
displayName="Custom BattleRoyale Addon"
displayURL="https://github.com/XColorful/CBR-addon/wiki"
logoFile="logo.png"
authors="XiaoColorful"
description='''Custom BattleRoyale author's CBR API usage reference mod
'''

[[dependencies.cbraddon]]
modId="${target_modloader}"
type="required"
versionRange="${target_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.cbraddon]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.cbraddon]]
modId = "battleroyale"
type="required"
versionRange = "[0.4.4-dev1,)"
ordering = "NONE"
side = "SERVER"